### ISSUE TITLE
Crash at start of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [JamCoreModding/Jamtastic#16]
Your latest release V1.0.3 is crashing for me at start of client.

https://bytebin.lucko.me/ss5ptxmQOY

**Comment by Jamalam360** [comment]
Yep sorry. It's an issue with one of the libraries Jamtastic uses. It should be fixed by tomorrow according to the maintainer

**Comment by Jamalam360** [comment]
I'm going to remove it from curseforge

**Comment by TheButterbrotMan** [comment]
Nope, it was another mod. STOP!

**Comment by Jamalam360** [comment]
There is an issue with the latest release though? It's been tested by myself and one other person 

If you know that it works then please say

**Comment by TheButterbrotMan** [comment]
Will test now. and provide log asap if it crashes.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/we5ZkHFtsn Confirmed! Is crashing.

**Comment by Jamalam360** [comment]
Yep. Same error as the others. The mod will have to be downgraded to 1.2.0 for now

**Comment by Jamalam360** [comment]
I have released V1.3.1, which temporarily removes the feature that was causing the crash. Once it is fixed I will add it back in, but for now you can get all but one of the V1.3.0 changes by using V1.3.1

CC: @TheButterbrotMan
