### ISSUE TITLE
Crash on server side only when placing water into jam pot

### ISSUE THREAD

**Issue by netcore10** [JamCoreModding/Jamtastic#17]
Doesn't happen in single player. Server crashed and almost broke the website xD
[crash-reports_crash-2022-04-20_09.29.06-server.txt](https://github.com/JamCoreModding/Jamtastic/files/8522403/crash-reports_crash-2022-04-20_09.29.06-server.txt)

Edit by Jamalam: https://www.toptal.com/developers/hastebin/fipoxuyilo.yaml

**Comment by Jamalam360** [comment]
Thanks for reporting, I'll look into it in a couple hours.

**Comment by Jamalam360** [comment]
@netcore10 this should be fixed in 1.3.2, but I don't have any way to test it atm. Can you try it out please, and reopen if it's broken still?

**Comment by netcore10** [comment]
@Jamalam360 Fixed!

**Comment by Jamalam360** [comment]
Awesome! Sorry about that.
