### ISSUE TITLE
more crashes on a server 

### ISSUE THREAD

**Issue by netcore10** [JamCoreModding/Jamtastic#18]
[crash-reports_crash-2022-04-21_10.49.15-server.txt](https://github.com/JamCoreModding/Jamtastic/files/8532511/crash-reports_crash-2022-04-21_10.49.15-server.txt)
[crash-2022-04-21_10.45.14-server.txt](https://github.com/JamCoreModding/Jamtastic/files/8532512/crash-2022-04-21_10.45.14-server.txt)

**Comment by Jamalam360** [comment]
@netcore10 thanks for reporting again.

Are you able to test a pre-release build for me plase? I'm fairly certain I have both of the issues fixed, but I _might_ have messed up jam names. Could you check that jam gets a name when it's created (i.e. something like `Beef and Mutton Preserve`)?

As mentioned before I don't have any infrastructure to test this on, unfortunately - my computer can't run a MC server and a client at the same time.

If you are able to test, [this is the link to the download via GitHub actions](https://github.com/JamCoreModding/Jamtastic/suites/6209558289/artifacts/219247379)

P.S, accidentally closed the issue because I wrote `half fix #18` in my commit message 😆

**Comment by netcore10** [comment]
sure i can give it a test

**Comment by netcore10** [comment]
no crash, but no name - I am running a custom modpack though

**Comment by netcore10** [comment]
![image](https://user-images.githubusercontent.com/181536/164529656-326cdc41-ce48-4237-8bbe-092e394b462e.png)

**Comment by Jamalam360** [comment]
hmm yeah I half expected that. let me figure something out and get back to you

**Comment by netcore10** [comment]
Hey, i'm just happy people don't crash atleast. I appreciate you doing all this.

**Comment by Jamalam360** [comment]
Issues are fine to fix when they're on mods that I enjoy working on, luckily jamtastic is one of them 😆

**Comment by netcore10** [comment]
> ahahaha i bet

The more complicated the mod, the harder it is to work on.

**Comment by Jamalam360** [comment]
Hello again :)

[This one uses a library to pull translations from the client](https://github.com/JamCoreModding/Jamtastic/suites/6211396183/artifacts/219518848)

🤞

**Comment by netcore10** [comment]
oop i may've been a dum and forgot to add it to my client xD

**Comment by netcore10** [comment]
nope still crash
[crash-2022-04-21_15.15.26-server.txt](https://github.com/JamCoreModding/Jamtastic/files/8534800/crash-2022-04-21_15.15.26-server.txt)

**Comment by Jamalam360** [comment]
Ok [this one](https://github.com/JamCoreModding/Jamtastic/suites/6212963958/artifacts/219630823) tries a completely different approach uses some custom networking packets

**Comment by netcore10** [comment]
that one caused a crash loop on the server without triggering an error.

**Comment by netcore10** [comment]
[logs_latest.log](https://github.com/JamCoreModding/Jamtastic/files/8541285/logs_latest.log)

**Comment by netcore10** [comment]
[latest.log](https://github.com/JamCoreModding/Jamtastic/files/8541311/latest.log)

**Comment by Jamalam360** [comment]
Oh god I did it again

**Comment by Jamalam360** [comment]
If [this](https://github.com/JamCoreModding/Jamtastic/suites/6222298103/artifacts/220280253) doesn't work I probably have to find a way to test locally on my computer :upside_down:

**Comment by netcore10** [comment]
WE GOT THERE \o/
![image](https://user-images.githubusercontent.com/181536/164758224-a3e95d28-4eb9-4682-8a00-fc33111d0b71.png)

**Comment by Jamalam360** [comment]
Ahahahahaha finally! Thank you so much for helping me test this out!

**Comment by netcore10** [comment]
You're welcome, i'll let you know if i find any server side problems but i think we can call this successful.

**Comment by Jamalam360** [comment]
V1.3.4 has the fix in it, it may take a while to show up on CurseForge since their weekend is Friday/Saturday
