### ISSUE TITLE
Feature Request: Compatibility with Sodium

### ISSUE THREAD

**Issue by Aaron995** [JamCoreModding/Jamtastic#9]
Hey! 
I love the look of this mod but sadly currently the game cannot launch whenever Jam and Sodium are both installed. 
[crash-2022-01-09_20.24.20-client.txt](https://github.com/JamCoreModding/JamFabric/files/7835752/crash-2022-01-09_20.24.20-client.txt)

**Comment by Jamalam360** [comment]
This looks like a consequence of a stupid fix I implemented when initially testing the mod. I'll look into how I could correct it

**Comment by Jamalam360** [comment]
I'm actually not sure what we're going to do here; Sodium compatibility would be very good, but they `@Overwrite` a method that this mod needs to inject into.

**Comment by Jamalam360** [comment]
This should be released by today; found a solution
